[package]
name = "modbus_rust"
version = "0.1.0"
authors = ["AlexandreFiale <afiale@agaetis.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modbus = "1.0.3"
